
---
jboss_user: jboss
jboss_group: jboss
jboss_install_dir: /opt/jboss-eap
jboss_zip: jboss-eap-8.0.0.zip
java_version_ubuntu: openjdk-8-jdk
java_version_rhel: java-1.8.0-openjdk
# defaults file for JbossEAP_Install
