---
- name: Install requied packages on RHEL
  ansible.builtin.yum:
    name:
      - java-11-openjdk
      - unzip
      - tar
      - wget
    state: present

- name: Create Jboss User
  ansible.builtin.user:
    name: "{{ jboss_user }}"
    state: present
    create_home: yes
    shell: /bin/bash

- name: Create Installation Directory
  ansible.builtin.file:
     path: "{{ jboss_install_dir }}"
     state: directory
     owner: "{{ jboss_user }}"
     group: "{{ jboss_group }} |default(jboss_group) }}"
     mode: '0755'
