---
- name: Copy Jboss EAP Installer
  ansible.builtin.copy:
    src: "{{ jboss_zip }}"
    dest: "/tmp/{{ jboss_zip | basename }}"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_user }} |default(jboss_user) }}"
    mode: '0644'
   
- name: Unzip Jboss EAP Installer
  ansible.builtin.unarchive:
    src: "/tmp/{{ jboss_zip | basename }}"
    dest: "{{ jboss_install_dir }}"
    remote_src: yes
    owner: "{{ jboss_user }}"
    group: "{{ jboss_user }} |default(jboss_user) }}"

- name: Set permissions for Jboss Installation Directory
  ansible.builtin.file:
    path: "{{ jboss_install_dir }}"
    state: directory
    recursive: yes
    owner: "{{ jboss_user }}"
    group: "{{ jboss_user }} |default(jboss_user) }}"