---
# tasks file for JbossEAP_Install
- name: Detect OS Family
  ansible.builtin.debug:
    msg: "Detected OS Family: {{ ansible_os_family }}"

- name: Run RHEL pre-tasks
  ansible.builtin.include_tasks: prereq_rhel.yml
  when: ansible_os_family == "RedHat"

- name: Run Ubuntu pre-tasks
  ansible.builtin.include_tasks: prereq_ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Run JBoss installation tasks
  ansible.builtin.include_tasks: install.yml

- name: Run JBoss service configuration tasks
  ansible.builtin.include_tasks: service.yml